name: Create and publish a Docker image
# https://docs.github.com/zh/actions/publishing-packages/publishing-docker-images
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Build admin and share
        run: sh ./build.sh
        env:
          CGO_ENABLED: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}